### ISSUE TITLE
Keyword plugin regex.search throws exception in 0.11.3

### ISSUE THREAD

**Issue by Tioborto** [Yelp/detect-secrets#115]
Hello, 

I've tested the new version and I get this error :

> Traceback (most recent call last):
  File "/home/.../detect-secrets-allprojects/venv/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/main.py", line 43, in main
    _perform_scan(args, plugins),
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/main.py", line 118, in _perform_scan
    args.all_files,
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/baseline.py", line 52, in initialize
    output.scan_file(file)
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/secrets_collection.py", line 185, in scan_file
    self._extract_secrets_from_file(f, filename_key)
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/secrets_collection.py", line 282, in _extract_secrets_from_file
    results.update(plugin.analyze(f, filename))
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/base.py", line 32, in analyze
    secrets = self.analyze_string(line, line_num, filename)
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/keyword.py", line 136, in analyze_string
    filetype=determine_file_type(filename),
  File "/home/.../detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/keyword.py", line 157, in secret_generator
    match = REGEX.search(lowered_string)

Do you have an idea ?

Best regards, 

Tioborto

**Comment by KevinHock** [comment]
Hi @Tioborto, thank you so much for the bug report, sorry about the bug. I merged this code (the keyword detector) last Friday.

Do you know what exception was thrown? Could you provide a small file to reproduce the error, if possible?

**Comment by Tioborto** [comment]
Hello @KevinHock ,
The error came from I parsed the result. The result output was in bytes.. I decode in utf-8 format. It works now

**Comment by Tioborto** [comment]
I've found another bug : 
```
Traceback (most recent call last):
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/main.py", line 43, in main
    _perform_scan(args, plugins),
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/main.py", line 118, in _perform_scan
    args.all_files,
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/baseline.py", line 52, in initialize
    output.scan_file(file)
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/secrets_collection.py", line 185, in scan_file
    self._extract_secrets_from_file(f, filename_key)
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/core/secrets_collection.py", line 282, in _extract_secrets_from_file
    results.update(plugin.analyze(f, filename))
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/base.py", line 32, in analyze
    secrets = self.analyze_string(line, line_num, filename)
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/keyword.py", line 136, in analyze_string
    filetype=determine_file_type(filename),
  File "/home/abortoluzzi59/detect-secrets-allprojects/venv/local/lib/python3.5/site-packages/detect_secrets/plugins/keyword.py", line 157, in secret_generator
    match = REGEX.search(lowered_string)
```
Have you ever had that mistake ?

**Comment by KevinHock** [comment]
Can you post the exception and not just the traceback @Tioborto?
