### ISSUE TITLE
meet unicode encode error while audit the baseline

### ISSUE THREAD

**Issue by saturbo** [Yelp/detect-secrets#211]
Hi , guys , I met the unicode encode error when I was trying to audit the baseline. The detail as below:
Filename:    src/main/java/com/XX/account/microservice/common/AccountConstants.java
Secret Type: Secret Keyword
----------
Traceback (most recent call last):
  File "/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/detect_secrets/main.py", line 64, in main
    audit.audit_baseline(args.filename[0])
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/audit.py", line 83, in audit_baseline
    original_baseline['plugins_used'],
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/audit.py", line 479, in _print_context
    force=force,
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/audit.py", line 586, in _get_secret_with_context
    snippet.highlight_line(raw_secret_value)
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/code_snippet.py", line 97, in highlight_line
    self.apply_highlight(self.target_line[index_of_payload:end_of_payload]),
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/code_snippet.py", line 114, in apply_highlight
    AnsiColor.RED_BACKGROUND,
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/color.py", line 17, in colorize
    AnsiColor.RESET.value,
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
     Seeking help with this error.

**Comment by KevinHock** [comment]
I’m currently on my phone, but a fix like #143 might work here, call you add that import at the top and see if it works for you? 👍

**Comment by KevinHock** [comment]
I’ll be sure to grep for .format( later and make sure this line is added, thanks for making this! 🙏

**Comment by saturbo** [comment]
@KevinHock  Thx. I add the code "from __future__ import unicode_literals" to both main.py and color.py  files and still not working.Below is the error message when audit the same file.For your reference.

Traceback (most recent call last):
  File "/usr/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/detect_secrets/main.py", line 64, in main
    audit.audit_baseline(args.filename[0])
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/audit.py", line 83, in audit_baseline
    original_baseline['plugins_used'],
  File "/usr/lib/python2.7/site-packages/detect_secrets/core/audit.py", line 481, in _print_context
    print(secret_with_context)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 55-56: ordinal not in range(128)

**Comment by saturbo** [comment]
@KevinHock  I add the code "sys.setdefaultencoding('utf-8')" in main.py by using utf-8 as default and it works fine with me now. Thx Kevin.

**Comment by OiCMudkips** [comment]
So I added an `.encode('utf-8')` to https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/core/code_snippet.py#L113 and it fixed things locally, but I don't know if this will work in Python 3. Probably needs more testing.

**Comment by domanchi** [comment]
Uncertain the action item to be taken here. Closing as fixed given the comment thread.
