### ISSUE TITLE
Updating baseline fails with version 0.14.0

### ISSUE THREAD

**Issue by shaikmanu797** [Yelp/detect-secrets#316]
```console
$ detect-secrets scan --update .secrets.baseline                
Traceback (most recent call last):
  File "/opt/miniconda3/envs/tests/bin/detect-secrets", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/tests/lib/python3.7/site-packages/detect_secrets/main.py", line 56, in main
    word_list_hash,
  File "/opt/miniconda3/envs/tests/lib/python3.7/site-packages/detect_secrets/main.py", line 141, in _perform_scan
    _get_plugins_from_baseline(old_baseline),
  File "/opt/miniconda3/envs/tests/lib/python3.7/site-packages/detect_secrets/main.py", line 101, in _get_plugins_from_baseline
    secrets_collection = SecretsCollection.load_baseline_from_dict(old_baseline)
  File "/opt/miniconda3/envs/tests/lib/python3.7/site-packages/detect_secrets/core/secrets_collection.py", line 131, in load_baseline_from_dict
    **plugin
  File "/opt/miniconda3/envs/tests/lib/python3.7/site-packages/detect_secrets/plugins/common/initialize.py", line 178, in from_plugin_classname
    klass = import_plugins(custom_plugin_paths)[plugin_classname]
TypeError: unhashable type: 'list'
```

**Comment by KevinHock** [comment]
Thanks for making this! I’ll have a look 👀

**Comment by schosterbarak** [comment]
also experiencing the same issue.

**Comment by KevinHock** [comment]
I missed a `tuple()` wrap at 

https://github.com/Yelp/detect-secrets/blob/f9888771b040b581bcf03fcebcdae65ed7341f3e/detect_secrets/core/secrets_collection.py#L118-L119

I will make a PR to fix, but feel free to `pip install -e .`, and at a `tuple()` call in the meantime.

**Comment by KevinHock** [comment]
Oh wow you maintain `checkov` @schosterbarak! A great tool.

**Comment by schosterbarak** [comment]
Thanks @KevinHock ! Are you using it today? Would appreciate any feedback :) trying to learn how ppl are using it (CI/ pre-commit) and how to improve

**Comment by KevinHock** [comment]
I have used it before @schosterbarak, but not yet in the CI/pre-commit phase, (mostly ran it then did `Counter(results).most_common()` to perform a one-time assessment). (I'm still in the requirements gather phase, looking at things like https://summitroute.github.io/aws_research/security_tool_comparison.html for example.)

Will definitely message you with feedback when I can be more helpful 👍

**Comment by KevinHock** [comment]
This issue can be closed now @shaikmanu797 👍 A [new version was released today](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#v0141).
