### ISSUE TITLE
AttributeError when running pre-commit hook under Windows

### ISSUE THREAD

**Issue by JohnNeville** [Yelp/detect-secrets#320]
My .pre-commit-config.yaml file is the following
```
-   repo: git@github.com:Yelp/detect-secrets
    rev: v0.14.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: packages.lock.json
```

When I run the command `pre-commit run` or `git commit` I get the following error
```
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

Traceback (most recent call last):
  File "c:\users\john.neville\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\john.neville\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\Scripts\detect-secrets-hook.EXE\__main__.py", line 7, in <module>
  File "c:\users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\lib\site-packages\detect_secrets\pre_commit_hook.py", line 27, in main
    args = parse_args(argv)
  File "c:\users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\lib\site-packages\detect_secrets\pre_commit_hook.py", line 21, in parse_args
    return ParserBuilder()\
  File "c:\users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\lib\site-packages\detect_secrets\core\usage.py", line 170, in parse_args
    PluginOptions(
  File "c:\users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\lib\site-packages\detect_secrets\core\usage.py", line 409, in __init__
    self.parser = parser.add_argument_group(
AttributeError: 'NoneType' object has no attribute 'add_argument_group'
```

This appears to be an error in both v0.14.0 and v.0.14.1 as downgrading to v0.13.1 does appear to work as expected under windows.

**Comment by KevinHock** [comment]
Somehow this function

https://github.com/Yelp/detect-secrets/blob/b5ae43ad574e81109b0062b3276a192e05354cef/detect_secrets/core/usage.py#L99-L114 is returning `None`. 

I am curious what `parser.prog` is in this case, could you edit `c:\users\john.neville\.cache\pre-commit\repog21r_7q6\py_env-python3.8\lib\site-packages\detect_secrets\core\usage.py` and print out what the `parser.prog` value is on line 107?

Thanks for giving this much info, most people don't :) I can make a PR to always return the parser (i.e. assume it is the pre-commit hook) if the `scan` subparser is not found. I am very curious what the `parser.prog` is though, on your system.

**Comment by JohnNeville** [comment]
It printed `detect-secrets-hook.EXE`

I suspect something along the lines of this would solve the problem without needing to add handling for the windows executable extension. 
```
if 'detect-secrets-hook' in parser.prog :
        return parser
```

**Comment by KevinHock** [comment]
.EXE makes sense, thanks!

Made the PR last night, was just curious what it could have been. Will merge after it gets a 🚢

**Comment by KevinHock** [comment]
I'll do the version bumping some time soon, thanks again @JohnNeville!

**Comment by KevinHock** [comment]
>some time soon
I'll bump tomorrow probably.

**Comment by KevinHock** [comment]
[_Released v0.14.2_](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#v0142)
