### ISSUE TITLE
Windows file not found 'clear'

### ISSUE THREAD

**Issue by aaronsteers** [Yelp/detect-secrets#333]
I'm receiving the following error message, whether I run under command prompt or powershell:

```
C:\Files\Source\dataops-infra>detect-secrets audit .secrets.baseline
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\detect-secrets.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\detect_secrets\main.py", line 73, in main
    audit.audit_baseline(args.filename[0])
  File "c:\python38\lib\site-packages\detect_secrets\core\audit.py", line 84, in audit_baseline
    _clear_screen()
  File "c:\python38\lib\site-packages\detect_secrets\core\audit.py", line 480, in _clear_screen
    subprocess.call(['clear'])
  File "c:\python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by KevinHock** [comment]
Ahh, I recently fixed a bug like this in another tool https://github.com/mandatoryprogrammer/TrustTrees/commit/5d2d267f72cd99db25cf464caac7c484ac33d2a3

Gonna label this one `first-good-issue`

**Comment by giuliogiaconi** [comment]
Has this issue been addressed in the end? I have the same problem and cannot get the audit window open. Thanks

**Comment by domanchi** [comment]
Thanks @pablosantiagolopez for helping fix this bug! This fix will go out with the new version.

**Comment by OVERPEY** [comment]
i have the same problem but on scan command . should i open  new Issue ?
