### ISSUE TITLE
unable to build pre-v1-launch

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#368]
I'm able to build and run the latest from the master branch, but after building the pre-v1-launch branch I get this with python 3.8:
```
$ PYTHONPATH=`pwd` python3 detect_secrets/main.py --version
Traceback (most recent call last):
  File "detect_secrets/main.py", line 1, in <module>
    import argparse
  File "/usr/lib64/python3.8/argparse.py", line 88, in <module>
    import re as _re
  File "/usr/lib64/python3.8/re.py", line 122, in <module>
    import enum
  File "/usr/lib64/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/data/ws/detect-secrets/detect_secrets/types.py", line 1, in <module>
    from typing import Any
  File "/usr/lib64/python3.8/typing.py", line 23, in <module>
    import contextlib
  File "/usr/lib64/python3.8/contextlib.py", line 7, in <module>
    from types import MethodType
ImportError: cannot import name 'MethodType' from partially initialized module 'types' (most likely due to a circular import) (/data/ws/detect-secrets/detect_secrets/types.py)
```
And a similar error on a different machine with Python 3.7:
```
$ PYTHONPATH=`pwd` python3 detect_secrets/main.py --version
Traceback (most recent call last):
  File "detect_secrets/main.py", line 1, in <module>
    import argparse
  File "/Users/gpflaum/miniconda2/envs/py37/lib/python3.7/argparse.py", line 87, in <module>
    import re as _re
  File "/Users/gpflaum/miniconda2/envs/py37/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/Users/gpflaum/miniconda2/envs/py37/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/gpflaum/ws/detect-secrets-pre-v1-launch/detect_secrets/types.py", line 1, in <module>
    from typing import Any
  File "/Users/gpflaum/miniconda2/envs/py37/lib/python3.7/typing.py", line 31, in <module>
    from types import WrapperDescriptorType, MethodWrapperType, MethodDescriptorType
ImportError: cannot import name 'WrapperDescriptorType' from 'types' (/Users/gpflaum/ws/detect-secrets-pre-v1-launch/detect_secrets/types.py)
```
And 3.6:
```
$ PYTHONPATH=`pwd` python3 detect_secrets/main.py --version
Traceback (most recent call last):
  File "detect_secrets/main.py", line 1, in <module>
    import argparse
  File "/usr/lib64/python3.6/argparse.py", line 87, in <module>
    import copy as _copy
  File "/usr/lib64/python3.6/copy.py", line 51, in <module>
    import types
  File "/data/ws/detect-secrets-pre-v1-launch/detect_secrets/types.py", line 1, in <module>
    from typing import Any
  File "/usr/lib64/python3.6/typing.py", line 4, in <module>
    import contextlib
  File "/usr/lib64/python3.6/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/lib64/python3.6/functools.py", line 22, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'
```
I'm using this to build:
```
python3 -m venv venv
source venv/bin/activate
pip install -r requirements-dev.txt
```

**Comment by domanchi** [comment]
@gpflaum , try doing:

```bash
python -m detect_secrets --version
```

instead.

**Comment by gpflaum** [comment]
Thank you that worked. My mistake for looking at the wrong version of CONTRIBUTING.md.
