### ISSUE TITLE
scanning fails if yaml transformer raises an exception

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#369]
I'm using the pre-v1-launch branch. Let me know if you'd prefer I not try using that branch yet.

When scanning a yaml file that has invalid syntax, the transformer raises an exception.

Expected result: skip yaml-specific scanning of the file
Actual result: the scan dies and there are no results for the repo

Example yaml file (should have quotes around the braces to be valid):
```yaml
metadata:
  name: {{ .Values.name }}
```
Scan failure:
```
$ detect-secrets scan
Traceback (most recent call last):
  File "/data/ws/detect-secrets/venv/bin/detect-secrets", line 11, in <module>
    load_entry_point('detect-secrets==0.14.3', 'console_scripts', 'detect-secrets')()
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 26, in main
    handle_scan_action(args)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 47, in handle_scan_action
    secrets = baseline.create(*args.path, should_scan_all_files=args.all_files)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/baseline.py", line 30, in create
    secrets.scan_file(filename)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/secrets_collection.py", line 43, in scan_file
    for secret in scan.scan_file(filename):
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/scan.py", line 49, in scan_file
    lines = _get_transformed_file(f)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/scan.py", line 126, in _get_transformed_file
    return transformer.parse_file(file)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/yaml.py", line 29, in parse_file
    for item in sorted(YAMLFileParser(file), key=lambda x: x.line_number):
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/yaml.py", line 148, in __iter__
    to_search = deque([self.json()])
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/yaml.py", line 139, in json
    return self.loader.get_single_data()
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 141, in construct_mapping
    raise ConstructorError("while constructing a mapping", node.start_mark,
yaml.constructor.ConstructorError: while constructing a mapping
  in "<unicode string>", line 2, column 9:
      name: {{ .Values.name }}
            ^
found unhashable key
  in "<unicode string>", line 2, column 10:
      name: {{ .Values.name }}
             ^
```

**Comment by domanchi** [comment]
@gpflaum : these issues are great! Thanks for being part of the beta test for v1.

I pushed a fix for this, and going to close it prematurely (to prevent pile up of issues while we're waiting for the branch to be reviewed). If this continues to be an issue, feel free to reopen.
