### ISSUE TITLE
scanning fails when config file transformer reads a binary file

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#370]
I'm using the pre-v1-launch branch.

When scanning a binary file, the config file transformer doesn't handle the UnicodeDecodeError raised by IniFileParser.

Expected result: skip the binary file
Actual result: the scan dies and there are no results for the repo

In this example, one binary file is skipped because ".woff" is in IGNORED_FILE_EXTENSIONS, but ".woff2" is not.
```
$ git clone https://github.com/puritycg/frontend-setup.git
$ detect-secrets -v scan frontend-setup/source/fonts
[scan]	INFO	Skipping "frontend-setup/source/fonts/fontawesome.woff" due to "detect_secrets.filters.heuristic.is_non_text_file"
[scan]	INFO	Checking file: frontend-setup/source/fonts/fontawesome.woff2
Traceback (most recent call last):
  File "/data/ws/detect-secrets/venv/bin/detect-secrets", line 11, in <module>
    load_entry_point('detect-secrets==0.14.3', 'console_scripts', 'detect-secrets')()
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 26, in main
    handle_scan_action(args)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 47, in handle_scan_action
    secrets = baseline.create(*args.path, should_scan_all_files=args.all_files)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/baseline.py", line 30, in create
    secrets.scan_file(filename)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/secrets_collection.py", line 42, in scan_file
    for secret in scan.scan_file(filename):
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/scan.py", line 49, in scan_file
    lines = _get_transformed_file(f)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/scan.py", line 126, in _get_transformed_file
    return transformer.parse_file(file)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/config.py", line 23, in parse_file
    return _parse_file(file)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/config.py", line 47, in _parse_file
    for key, value, line_number in IniFileParser(file, add_header=add_header):
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/transformers/config.py", line 90, in __init__
    content = file.read()
  File "/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 18: invalid start byte
```

**Comment by domanchi** [comment]
Another great catch, another straight forward fix. Keep them coming!
