### ISSUE TITLE
scanning fails when scan_file calls f.readlines() on a binary file

### ISSUE THREAD

**Issue by gpflaum** [Yelp/detect-secrets#371]
I'm using the pre-v1-launch branch.

f.readlines() called by scan_file can raise UnicodeDecodeError.

Expected result: skip the binary file
Actual result: the scan dies and there are no results for the repo

```
$ git clone https://github.com/t3hami/t3hami.github.io-old.git
$ detect-secrets -v scan t3hami.github.io-old
[scan]	INFO	Checking file: t3hami.github.io-old/.gitignore
[scan]	INFO	Checking file: t3hami.github.io-old/.travis.yml
[scan]	INFO	Checking file: t3hami.github.io-old/LICENSE
[scan]	INFO	Checking file: t3hami.github.io-old/README.md
[scan]	INFO	Checking file: t3hami.github.io-old/gulpfile.js
[scan]	INFO	Checking file: t3hami.github.io-old/index.html
[scan]	INFO	Checking file: t3hami.github.io-old/package.json
[scan]	INFO	Checking file: t3hami.github.io-old/pronounce.wav
Traceback (most recent call last):
  File "/data/ws/detect-secrets/venv/bin/detect-secrets", line 11, in <module>
    load_entry_point('detect-secrets==0.14.3', 'console_scripts', 'detect-secrets')()
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 26, in main
    handle_scan_action(args)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/main.py", line 47, in handle_scan_action
    secrets = baseline.create(*args.path, should_scan_all_files=args.all_files)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/baseline.py", line 30, in create
    secrets.scan_file(filename)
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/secrets_collection.py", line 42, in scan_file
    for secret in scan.scan_file(filename):
  File "/data/ws/detect-secrets/venv/lib64/python3.8/site-packages/detect_secrets-0.14.3-py3.8.egg/detect_secrets/core/scan.py", line 51, in scan_file
    lines = f.readlines()
  File "/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 4: invalid continuation byte
```

**Comment by domanchi** [comment]
This has also been fixed when fixing #370. Closing as done.
