### ISSUE TITLE
Auditing (with report) an empty/clean baseline result to a ZeroDivisionError

### ISSUE THREAD

**Issue by llicour** [Yelp/detect-secrets#388]
version 0.14.3
Steps to reproduce :
(from an clean-or-empty project)
```
detect-secrets scan > .secrets.baseline
detect-secrets audit .secrets.baseline --display-result    
Traceback (most recent call last):
  File ".pyenv/versions/venv-py37/bin/detect-secrets", line 8, in <module>
    sys.exit(main())
  File ".pyenv/versions/venv-py37/lib/python3.7/site-packages/detect_secrets/main.py", line 77, in main
    audit.print_audit_results(args.filename[0])
  File ".pyenv/versions/venv-py37/lib/python3.7/site-packages/detect_secrets/core/audit.py", line 331, in print_audit_results
    baseline_filename,
  File ".pyenv/versions/venv-py37/lib/python3.7/site-packages/detect_secrets/core/audit.py", line 297, in determine_audit_results
    total
ZeroDivisionError: float division by zero

cat .secrets.baseline
{
  "custom_plugin_paths": [],
  "exclude": {
    "files": null,
    "lines": null
  },
  "generated_at": "2021-01-06T06:26:46Z",
  "plugins_used": [
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "ArtifactoryDetector"
    },
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "keyword_exclude": null,
      "name": "KeywordDetector"
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "results": {},
  "version": "0.14.3",
  "word_list": {
    "file": null,
    "hash": null
  }
}
```

**Comment by domanchi** [comment]
This is fixed in the upcoming v1 branch.

```
$ cat .secrets.baseline
{
  "generated_at": "2021-01-06T21:16:59Z",
  "version": "1.0.0",
  "plugins_used": [
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "name": "Base64HighEntropyString"
    },
    {
      "name": "HexHighEntropyString"
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "name": "KeywordDetector"
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "filters_used": [
    {
      "path": "detect_secrets.filters.heuristic.is_potential_uuid"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_likely_id_string"
    },
    {
      "path": "detect_secrets.filters.heuristic.is_sequential_string"
    },
    {
      "path": "detect_secrets.filters.allowlist.is_line_allowlisted"
    },
    {
      "path": "detect_secrets.filters.common.is_ignored_due_to_verification_policies",
      "min_level": 2
    }
  ],
  "results": {}
}
$ detect-secrets audit --stats --json .secrets.baseline
[]
```

Since all development effort is focused towards getting v1 out the door, I will close this as resolved, and recommend you upgrade your version when that is ready.

If you would like to be a part of the beta testing group, feel free to check out: https://github.com/Yelp/detect-secrets/tree/pre-v1-launch.
