### ISSUE TITLE
detect-secrets 1.0.0 pre-commit hook broken

### ISSUE THREAD

**Issue by michael-anselmi** [Yelp/detect-secrets#407]
Hi, and congrats on releasing version 1.0.0 of detect-secrets!  I feel bad filing the first bug report against this new version, but the pre-commit hook / `setup.py` is broken.  I'm using pre-commit version 2.10.1, the latest version.

To reproduce:

1. Have a `.pre-commit-config.yaml` file like this:

```yaml
repos:

  - repo: 'https://github.com/Yelp/detect-secrets'
    rev: 'v1.0.0'
    hooks:
      - id: 'detect-secrets'
```

2. Run `pre-commit run --all-files`.

3. Observe output like this:

```
[INFO] Installing environment for https://github.com/Yelp/detect-secrets.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/manselmi/.cache/pre-commit/repo4vblkajn/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Looking in indexes: http://localhost:3141/root/local/+simple/
    Processing /Users/manselmi/.cache/pre-commit/repo4vblkajn

stderr:
        ERROR: Command errored out with exit status 1:
         command: /Users/manselmi/.cache/pre-commit/repo4vblkajn/py_env-python3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders
/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5
t/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exe
c'"'"'))' egg_info --egg-base /private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-pip-egg-info-ucyg6p6p
             cwd: /private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/
        Complete output (19 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/setup.py", line 4, in <module>
            from detect_secrets.__version__ import VERSION
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/__init__.py", line 1, in <module>
            from .core.secrets_collection import SecretsCollection  # noqa: F401
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/core/secrets_collection.py", line 11, in <module>
            from . import scan
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/core/scan.py", line 24, in <module>
            from .plugins import Plugin
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/core/plugins/__init__.py", line 1, in <module>
            from . import initialize    # noqa: F401
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/core/plugins/initialize.py", line 9, in <module>
            from .util import get_mapping_from_secret_type_to_class
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/core/plugins/util.py", line 13, in <module>
            from ...plugins.base import BasePlugin
          File "/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-req-build-638l7i5t/detect_secrets/plugins/base.py", line 19, in <module>
            import requests
        ModuleNotFoundError: No module named 'requests'
        ----------------------------------------
    WARNING: Discarding file:///Users/manselmi/.cache/pre-commit/repo4vblkajn. Command errored out with exit status 1: python setup.py egg_info Check the logs for full
command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Check the log at /Users/manselmi/.cache/pre-commit/pre-commit.log
```

There is a chicken-and-egg problem in `setup.py`.  `setup.py` imports `detect_secrets` before running the setuptools code that installs runtime dependencies such as requests, and since those dependencies are not yet available, we get a `ModuleNotFoundError`.

**Comment by michael-anselmi** [comment]
You may notice in the example above that I was not using the PyPI index, but the issue still occurs when installing from PyPI.

**Comment by cbows** [comment]
I have made a PR that should fix the problem. I avoid importing the module by just parsing the text in `__version__.py` directly. It's not very robust currently (you could use a regex if you like). but I think using something like [setuptools_scm](https://github.com/pypa/setuptools_scm) is a cleaner solution anyway.

**Comment by domanchi** [comment]
I tested this with the patch, and it seems to work now.

```bash
$ cat .pre-commit-config.yaml
...
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
$ PIP_DEFAULT_INDEX_URL='https://test.pypi.org/simple/' pre-commit run
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/aaronloo/.cache/pre-commit/patch1614267034.
Check builtin type constructor use...................(no files to check)Skipped
Check docstring is first.............................(no files to check)Skipped
Debug Statements (Python)............................(no files to check)Skipped
Fix double quoted strings............................(no files to check)Skipped
Fix End of Files.........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Reorder python imports...............................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
autopep8.............................................(no files to check)Skipped
Detect secrets...........................................................Passed
[INFO] Restored changes from /Users/aaronloo/.cache/pre-commit/patch1614267034.
```

Will deploy to public PyPI. Thanks for reporting this so quickly!

**Comment by AIGeneratedUsername** [comment]
```
Updating https://github.com/Yelp/detect-secrets ... [INFO] Initializing environment for https://github.com/Yelp/detect-secrets.
updating v0.14.3 -> v1.0.0.
```


Well... Now it is broken again.

**Comment by domanchi** [comment]
@AIGeneratedUsername : can you provide reproduction steps? It looks like you're updating to the broken version.

**Comment by AIGeneratedUsername** [comment]
> can you provide reproduction steps?

The issue is that `pre-commit autoupdate` updated the version to the "1.0.0" (instead of 1.0.1").

>  It looks like you're updating to the broken version.

Yep, you are correct. Now it works. I set the version manually in the ".pre-commit-config.yaml" file:
```

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
```

Thank you for your response.
