### ISSUE TITLE
 path: str  SyntaxError: invalid syntax error on windows

### ISSUE THREAD

**Issue by s1mrankaur** [Yelp/detect-secrets#451]
Attached error message below

```
$ detect-secrets scan
Traceback (most recent call last):
  File "c:\users\documents\build-environments\py2.7.17-64\python27-64\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\documents\build-environments\py2.7.17-64\python27-64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Documents\build-environments\py2.7.17-64\Python27-64\Scripts\detect-secrets.exe\__main__.py", line 4, in <module>
  File "c:\users\documents\build-environments\py2.7.17-64\python27-64\lib\site-packages\detect_secrets\__init__.py", line 1, in <module>
    from .core.secrets_collection import SecretsCollection  # noqa: F401
  File "c:\users\documents\build-environments\py2.7.17-64\python27-64\lib\site-packages\detect_secrets\core\secrets_collection.py", line 18
    path: str
        ^
SyntaxError: invalid syntax

```

**Comment by domanchi** [comment]
You're using python2.7. `detect-secrets` dropped python2.7 support a while ago.
