### ISSUE TITLE
PotentialSecret line_number part 2

### ISSUE THREAD

**Issue by js-truework** [Yelp/detect-secrets#479]
A follow up to  https://github.com/Yelp/detect-secrets/issues/471, I am still getting issues around PotentialSecret objects. Looks like the previous traceback was obscuring the underlying problem.

```
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/bin/detect-secrets-hook", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/lib/python3.9/site-packages/detect_secrets/pre_commit_hook.py", line 61, in main
    baseline.save_to_file(args.baseline, filename=args.baseline_filename)
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/lib/python3.9/site-packages/detect_secrets/core/baseline.py", line 109, in save_to_file
    output = format_for_output(secrets)
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/lib/python3.9/site-packages/detect_secrets/core/baseline.py", line 74, in format_for_output
    'results': secrets.json(),
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/lib/python3.9/site-packages/detect_secrets/core/secrets_collection.py", line 199, in json
    output[filename].append(secret.json())
  File "/home/runner/.cache/pre-commit/repo2j0bg4ba/py_env-python3.9/lib/python3.9/site-packages/detect_secrets/core/potential_secret.py", line 106, in json
    if self.line_number:
AttributeError: 'PotentialSecret' object has no attribute 'line_number'
```

**Comment by lorenzodb1** [comment]
Hi @js-truework, thank you for reporting this!

I pushed a tentative fix as part of #529. I'll go ahead and close this issue, but please let me know if the problem arises again.
