### ISSUE TITLE
Error installing  gibberish-detector

### ISSUE THREAD

**Issue by vrokida** [Yelp/detect-secrets#491]
Hello !

We are not able to install Gibberish Detector. 

We try 
`
pip install detect-secrets[gibberish]
`
and we get
`
no matches found: detect-secrets[gibberish]
`

We are using  detect-secrets version 1.1.0 .
We tried also installing gibberish-detector and then ` pip install detect-secrets[gibberish]` but I got same results. 

We appreciate any help

**Comment by domanchi** [comment]
@vrokida : not sure why it isn't working for you -- maybe check your network connections, or PyPI indexes.

This is my output when I attempt:

```
$ pip install detect-secrets[gibberish]
Collecting detect-secrets[gibberish]
  Downloading detect_secrets-1.1.0-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 8.8 MB/s
Collecting pyyaml
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 11.0 MB/s
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting gibberish-detector
  Using cached gibberish_detector-0.1.1-py3-none-any.whl (10 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, pyyaml, gibberish-detector, detect-secrets
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.9 detect-secrets-1.1.0 gibberish-detector-0.1.1 idna-3.3 pyyaml-6.0 requests-2.26.0 urllib3-1.26.7
```

**Comment by loadaverage** [comment]
Another story with enabling gibberish. I had `ModuleNotFoundError` exception while trying to use pre-commit with latest detect-secrets (v1.1.0):
```
ModuleNotFoundError: No module named 'gibberish_detector'
```
Because gibberish_detector is an extra dependency, it could be installed with `additional_dependencies` of pre-commit hook:
```yaml
repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ['gibberish-detector']
```

**Comment by jlongland** [comment]
@vrokida [] I wager you're using zsh. It uses [square brackets for globbing / pattern matchin](http://zsh.sourceforge.net/Guide/zshguide05.html#l137)

This should work: `pip install 'detect-secrets[gibberish]'`

**Comment by jpdakran** [comment]
@vrokida Hello. Are you still experiencing this issue with the latest version of detect-secrets?

**Comment by jpdakran** [comment]
Closing due to no further updates provided. If you have any other questions or you do not consider this resolved - please re-open an issue and the team will be happy to assist. Thanks!

**Comment by jawadqur** [comment]
All of a sudden this is starting to affect some of my pre-commit hooks. Is it possible to not use gibberish detector in my pre-commit? 

```
repos:
-   repo: git@github.com:Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: poetry.lock
```


```
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Detect secrets...........................................................Failed
- hook id: detect-secrets
- exit code: 1

Traceback (most recent call last):
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/bin/detect-secrets-hook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/pre_commit_hook.py", line 20, in main
    args = parse_args(argv)
           ^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/pre_commit_hook.py", line 79, in parse_args
    output = ParserBuilder().add_pre_commit_arguments().parse_args(argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/usage/__init__.py", line 160, in parse_args
    processor(args)
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/usage/baseline.py", line 31, in parse_args
    args.baseline = baseline.load(loaded_baseline, filename=args.baseline_filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/baseline.py", line 51, in load
    configure_settings_from_baseline(baseline, filename=filename)
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/settings.py", line 50, in configure_settings_from_baseline
    filters.gibberish.initialize(
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/filters/gibberish/__init__.py", line 37, in initialize
    model = get_model()
            ^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/filters/gibberish/__init__.py", line 94, in get_model
    from gibberish_detector.model import Model
ModuleNotFoundError: No module named 'gibberish_detector'
Traceback (most recent call last):
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/bin/detect-secrets-hook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/pre_commit_hook.py", line 20, in main
    args = parse_args(argv)
           ^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/pre_commit_hook.py", line 79, in parse_args
    output = ParserBuilder().add_pre_commit_arguments().parse_args(argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/usage/__init__.py", line 160, in parse_args
    processor(args)
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/usage/baseline.py", line 31, in parse_args
    args.baseline = baseline.load(loaded_baseline, filename=args.baseline_filename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/core/baseline.py", line 51, in load
    configure_settings_from_baseline(baseline, filename=filename)
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/settings.py", line 50, in configure_settings_from_baseline
    filters.gibberish.initialize(
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/filters/gibberish/__init__.py", line 37, in initialize
    model = get_model()
            ^^^^^^^^^^^
  File "/Users/qureshi/.cache/pre-commit/repo47441abh/py_env-python3.12/lib/python3.12/site-packages/detect_secrets/filters/gibberish/__init__.py", line 94, in get_model
    from gibberish_detector.model import Model
ModuleNotFoundError: No module named 'gibberish_detector'

```
