### ISSUE TITLE
error in installation 

### ISSUE THREAD

**Issue by rafaelsilvaa10** [Yelp/detect-secrets#500]
hello i'm getting this error when trying to run detect secrets:

```
Traceback (most recent call last):
  File "/usr/local/bin/detect-secrets", line 7, in <module>
    from detect_secrets.main import main
  File "/usr/local/lib/python3.5/dist-packages/detect_secrets/__init__.py", line 1, in <module>
    from .core.secrets_collection import SecretsCollection  # noqa: F401
  File "/usr/local/lib/python3.5/dist-packages/detect_secrets/core/secrets_collection.py", line 18
    path: str
        ^
SyntaxError: invalid syntax
```

```
version python 

/home/jenkins# python --version
Python 3.5.3
```

installation 
`pip3 install detect-secrets[word_list]`

Has anyone faced this error?

**Comment by jpdakran** [comment]
@rafaelsilvaa10 Python 3.5 has been end of life since 2015. Can you test with an updated version of python and updated version of detect-secrets?

**Comment by jpdakran** [comment]
Hi @rafaelsilvaa10. We have just dropped support python 3.6. Please try python 3.7+ and let us know if this works.
