### ISSUE TITLE
Windows file not found 

### ISSUE THREAD

**Issue by OVERPEY** [Yelp/detect-secrets#606]
im receiving the following error message, on windows 10 : 

> D:\BugHunter\test>detect-secrets scan > .secrets.baseline
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\detect-secrets.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\detect_secrets\main.py", line 30, in main
    handle_scan_action(args)
  File "C:\Python310\lib\site-packages\detect_secrets\main.py", line 70, in handle_scan_action
    secrets = baseline.create(
  File "C:\Python310\lib\site-packages\detect_secrets\core\baseline.py", line 34, in create
    secrets.scan_files(
  File "C:\Python310\lib\site-packages\detect_secrets\core\scan.py", line 72, in get_files_to_scan
    valid_paths = git.get_tracked_files(git.get_root_directory(root))
  File "C:\Python310\lib\site-packages\detect_secrets\util\git.py", line 18, in get_root_directory
    return subprocess.check_output(command).decode('utf-8').strip()
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

detect-secrets : 1.3.0
Windows Build : 19044.1706

**Comment by lorenzodb1** [comment]
Hi @OVERPEY, thank you for bringing up this issue. In order for us to better review it, could you please tell us if you had an existing baseline file present before incurring in this error? Have you tried running our current unit tests? If yes, do those pass? Could you also try using previous versions of detect-secrets and see if the same error occurs?

**Comment by cybersholt** [comment]
Having the same issue with:
detect-secrets: 1.4.0 
OS: Windows 10 Pro
OS Build: 19043.2251

I created the baseline first as outlined in the docs, I have not tried the unit tests yet. 

## detect-secrets audit .secrets.baseline 
```
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\detect_secrets\core\baseline.py", line 61, in load_from_file
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.secrets.baseline'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\detect-secrets.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\detect_secrets\main.py", line 32, in main
    handle_audit_action(args)
  File "c:\python39\lib\site-packages\detect_secrets\main.py", line 152, in handle_audit_action
    audit.audit_baseline(args.filename[0])
  File "c:\python39\lib\site-packages\detect_secrets\audit\audit.py", line 22, in audit_baseline
    secrets = get_baseline_from_file(filename)
  File "c:\python39\lib\site-packages\detect_secrets\audit\common.py", line 31, in get_baseline_from_file
    return baseline.load(baseline.load_from_file(filename), filename)
  File "c:\python39\lib\site-packages\detect_secrets\core\baseline.py", line 64, in load_from_file
    raise UnableToReadBaselineError from e
detect_secrets.exceptions.UnableToReadBaselineError
```
## pip show detect-secrets 
```
Name: detect-secrets
Version: 1.4.0
Summary: Tool for detecting secrets in the codebase
Home-page: https://github.com/Yelp/detect-secrets
Author: Aaron Loo
Author-email: aaronloo@yelp.com
License: Copyright Yelp, Inc. 2020
Location: c:\python39\lib\site-packages
Requires: pyyaml, requests
Required-by:
```

## pip debug
```
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 22.3.1 from C:\Python39\lib\site-packages\pip (python 3.9)
sys.version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
sys.executable: C:\Python39\python.exe
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: cp1252
sys.platform: win32
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): C:\Python39\lib\site-packages\pip\_vendor\certifi\cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.5
  distlib==0.3.6
  distro==1.7.0
  msgpack==1.0.4
  packaging==21.3
  pep517==0.13.0
  platformdirs==2.5.2
  pyparsing==3.0.9
  requests==2.28.1
  certifi==2022.09.24
  chardet==5.0.0
  idna==3.4
  urllib3==1.26.12
  rich==12.5.1 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.13.0
  typing_extensions==4.4.0 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.8.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.1.0 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 33
  cp39-cp39-win_amd64
  cp39-abi3-win_amd64
  cp39-none-win_amd64
  cp38-abi3-win_amd64
  cp37-abi3-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  ...
  [First 10 tags shown. Pass --verbose to show all.]
```

**Comment by cybersholt** [comment]
Following up regarding this: I managed to get it working with WSL which happened to have python 3.8 on it, the error message produced gave me a hint on how to fix it specifically: **UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte**

Turns out that the file generated by the Windows version had the character encoding set to UTF-16 BE BOM, not sure why I'm on a US / English system. Simply changing the character encoding to UTF-8 ( with Notepad++ ), saving the file and executing it again fixed the issue for both WSL2 ( ubuntu ) & for Windows. 

```
File "/home/cybersholt/.local/lib/python3.8/site-packages/detect_secrets/core/baseline.py", line 62, in load_from_file
    return cast(Dict[str, Any], json.loads(f.read()))
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
```

**Comment by jpdakran** [comment]
Glad to hear this is working now.
