### ISSUE TITLE
-v Verbosity overflow, 3+ v's cause a KeyError

### ISSUE THREAD

**Issue by KevinHock** [Yelp/detect-secrets#61]
Repro: `detect-secrets --scan . -vvv`

Here lies the relevant stack trace:

```python
Traceback (most recent call last):
  File "/hey/three_six/bin/detect-secrets", line 11, in <module>
    sys.exit(main())
  File "/hey/three_six/lib/python3.6/site-packages/detect_secrets/main.py", line 27, in main
    log.set_debug_level(args.verbose)
  File "/hey/three_six/lib/python3.6/site-packages/detect_secrets/core/log.py", line 46, in _set_debug_level
    self.setLevel(mapping[debug_level])
KeyError: 3
```

**Comment by KevinHock** [comment]
Fixed by https://github.com/Yelp/detect-secrets/pull/65/commits/0b2700251f03d96757349a87fc07425dc0a4973b
